#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
$HOME/.config/polybar/launch.sh &
#$HOME/.config/bspwm/monitor.sh
ibus-daemon -rdxR
#pulseaudio &
picom &

#wallpaper and theme
#wal -i $HOME/.config/wallpaper &
. "$HOME/.cache/wal/colors.sh"
feh --bg-scale $HOME/.config/wal/wal

nm-applet


#bspc monitor -d I II III IV V VI VII VIII IX X
bspc monitor "eDP1" -d VII VIII IX X
bspc monitor "HDMI2" -d I II III IV V VI

# Config when switch from 1 monitor to 2 monitor
# and vice versa
#m=$(bspc query -M | wc -l)

#if [ "$m" = 1 ]; then
#	bspc monitor "HDMI2" -r
#	bspc monitor "eDP1" -d I II III IV V VI VII
#elif ["$m" = 2 ]; then
#	bspc monitor "eDP1" -d VII VIII IX X
#	bspc monitor "HDMI2" -d I II III IV V VI
#else
#	bspc monitor "eDP1" -d ""
#fi


bspc config border_width         2
bspc config window_gap           5
#bspc config border_radius	0.5
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color15"
#bspc config focus_follows_pointer true

#bspc rule -a Firefox desktop='^1'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off
bspc rule -a Opera desktop='^6'
