/* -*- Mode: Javascript; tab-width: 3; indent-tabs-mode: nil; c-basic-offset: 3 -*- */
/*
* DejaClick for Chrome by SmartBear Software.
* Copyright (C) 2006-2013 SmartBear Software.  All Rights Reserved.
*
* The contents of this file are subject to the End User License Agreement.
* Software distributed under the License is distributed on an "AS IS" basis,
* WITHOUT WARRANTY OF ANY KIND, either express or implied. See the License
* for the specific language governing rights and limitations under the
* License.
*/

'use strict';

/*global DejaClick*/


/**
 * Collection of constants used throughout DejaClick.
 * @type {!Object.<string,(integer|string)>}
 * @const
 */
DejaClick.constants = {

   // valid deja run-modes
   RUNMODE_INACTIVE: 0,
   RUNMODE_STOPPED: 1,
   RUNMODE_RECORD: 2,
   RUNMODE_REPLAY: 3,
   RUNMODE_PAUSED: 4,
   RUNMODE_SUSPEND: 5,
   RUNMODE_RESUME: 6,
   RUNMODE_RECORD_APPEND: 7,

   RUNTYPE_INACTIVE : 0,
   RUNTYPE_STOPABORTED : 1,
   RUNTYPE_STOPNOSCRIPT : 2,
   RUNTYPE_STOPLOADED : 3,
   RUNTYPE_REPLAY : 4,
   RUNTYPE_PAUSED : 5,
   RUNTYPE_RECORDNEW : 6,
   RUNTYPE_RECORDAPPEND : 7,
   
   // valid wait modes
   WAITMODE_INACTIVE : 0,
   WAITMODE_READY : 1,
   WAITMODE_BUSY : 2,

   // valid wait (sub)types
   WAITTYPE_INACTIVE      : 0,
   WAITTYPE_LOADING       : 1,
   WAITTYPE_SAVING        : 2,
   WAITTYPE_LOADREMOTE    : 3,
   WAITTYPE_SAVEREMOTE    : 4,
   WAITTYPE_PAUSING       : 5,
   WAITTYPE_PAUSED        : 6,
   WAITTYPE_STOPPING      : 7,
   WAITTYPE_STOPPED       : 8,
   WAITTYPE_INITIALIZING  : 9,
   WAITTYPE_DISPATCHING   : 10,
   WAITTYPE_PROCESSING    : 11,
   WAITTYPE_SKIPPING      : 12,
   WAITTYPE_ANALYZING     : 13,
   WAITTYPE_VALIDATING    : 14,
   WAITTYPE_LOADINGDOC    : 15,
   WAITTYPE_LOCATIONCHG   : 16,
   WAITTYPE_THINKTIME     : 17,
   WAITTYPE_LOCATIONS     : 18,
   WAITTYPE_MUTATIONS     : 19,
   WAITTYPE_BROWSERS      : 20,
   WAITTYPE_NETWORK       : 21,
   WAITTYPE_CACHE         : 22,
   WAITTYPE_CLASSIFYTIME  : 23,

   BREAKPOINT_TYPE_NONE     : 0,
   BREAKPOINT_RECORD_APPEND : 1,

   STATUS_SUCCESS: 0,
   STATUS_CONNECTION_FAILURE: 1,
   STATUS_SERVER_TIMEOUT: 2,
   STATUS_INVALID_RESPONSE: 3,
   STATUS_VALIDATION_FAILURE: 5,
   STATUS_NO_RESPONSE: 6,
   STATUS_HTTP_ERROR: 7,
   STATUS_REDIRECTION: 8,
   STATUS_PING_FAILURE: 9,
   STATUS_ADDRESS_RESOLUTION_FAILED: 51,
   STATUS_BROWSER_TIMEOUT: 82,
   STATUS_BROWSER_TIMEOUT_TRANSACTION: 81,
   STATUS_BROWSER_TIMEOUT_EVENT: 82,
   STATUS_BROWSER_TIMEOUT_RESPONSE: 83,
   STATUS_BROWSER_TIMEOUT_LOCATION: 84,
   STATUS_BROWSER_TIMEOUT_MUTATION: 85,
   STATUS_BROWSER_TIMEOUT_NETWORK: 86,
   STATUS_BROWSER_TIMEOUT_NAVIGATE: 89,
   STATUS_INTERNAL_ERROR: 90,
   STATUS_MATCH_SCORE_FAILURE: 91,
   STATUS_SKIPPED_EVENTS: 92,
   STATUS_UNEXPECTED_DIALOG: 93,
   STATUS_TOO_MANY_STEPS: 94,
   STATUS_SCRIPT_PARSE_ERROR: 96,
   STATUS_TARGET_ELEMENT_NOT_FOUND: 97,
   STATUS_CUSTOM_ERROR: 988,

   TREELEVEL_SCRIPT: 0,
   TREELEVEL_ACTION: 1,
   TREELEVEL_EVENT: 2,

   // Screen, source, header capture progress status.
   CAPTURE_READY: 1,
   CAPTURE_PENDING: 2,
   CAPTURE_COMPLETE: 3,

   DC_AUTOPAUSE_NONE: 0,
   DC_AUTOPAUSE_ACTION: 1,
   DC_AUTOPAUSE_EVENT: 2,
   
   DC_FPDOC: 'dcdocid',         // DOM tree document fingerprint
   DC_INPUTVAL: 'dcvalue',      // original FORM input value

   DISPLAYLEVEL_MIN: 0,
   DISPLAYLEVEL_BASIC: 0,
   DISPLAYLEVEL_ADVANCED: 1,
   DISPLAYLEVEL_DIAGNOSTIC: 2,
   DISPLAYLEVEL_MAX: 2,

   AUTOPAUSE_MIN: 0,
   AUTOPAUSE_NONE: 0,
   AUTOPAUSE_ACTION: 1,
   AUTOPAUSE_EVENT: 2,
   AUTOPAUSE_MAX: 2,

   MINMUTATIONS_MIN: 0,
   MINMUTATIONS_MAX: 999999,

   MAXSKIPPEDEVENTS_MIN: 1,
   MAXSKIPPEDEVENTS_MAX: 999,

   RESPONSETIMEOUT_MIN: 0,
   RESPONSETIMEOUT_MAX: 99999,

   EVENTDELAY_MIN: 0,
   EVENTDELAY_FASTER: 10,
   EVENTDELAY_NORMAL: 100,
   EVENTDELAY_SLOWER: 400,
   EVENTDELAY_MAX: 99999,

   DISPATCHDELAY_MIN: 0,
   DISPATCHDELAY_FASTER: 10,
   DISPATCHDELAY_NORMAL: 30,
   DISPATCHDELAY_SLOWER: 100,
   DISPATCHDELAY_MAX: 99999,

   READYTIMEOUT_MIN: 0,
   READYTIMEOUT_FASTER: 10,
   READYTIMEOUT_NORMAL: 50,
   READYTIMEOUT_SLOWER: 200,
   READYTIMEOUT_MAX: 99999,

   EVENTTIMEOUT_MIN: 0,
   EVENTTIMEOUT_MAX: 999999,

   NETWORKTIMEOUT_MIN: 0,
   NETWORKTIMEOUT_MAX: 999999,

   NETPRUNETIMEOUT_MIN: 0,
   NETPRUNETIMEOUT_MAX: 999999,

   LOCATIONTIMEOUT_MIN: 0,
   LOCATIONTIMEOUT_MAX: 360000,

   MUTATIONBEGINTIMEOUT_MIN: 0,
   MUTATIONBEGINTIMEOUT_MAX: 999999,

   MUTATIONENDTIMEOUT_MIN: 0,
   MUTATIONENDTIMEOUT_MAX: 999999,

   NAVIGATIONTIMEOUT_MIN: 0,
   NAVIGATIONTIMEOUT_MAX: 99999,

   EVENTSPEED_MIN: 0.01,
   EVENTSPEED_MAX: 9.99,

   MUTATIONDELAY_MIN: 0,
   MUTATIONDELAY_MAX: 99999,

   MAXSCRIPTRUN_MIN: 0,
   MAXSCRIPTRUN_MAX: 999,

   PORTNUMBER_MIN: 0,
   PORTNUMBER_MAX: 65535,

   SUSPENDDELAY_MIN: 0,
   SUSPENDDELAY_MAX: 99999,

   WATCHDINTERVAL_MIN: 1000,
   WATCHDINTERVAL_MAX: 3600000,

   QUITAPPDELAY_MIN: 0,
   QUITAPPDELAY_MAX: 99999,

   KEYWORDVALTIMEOUT_MIN: 0,
   KEYWORDVALTIMEOUT_MAX: 60000,
   
   JAVASCRIPTVALTIMEOUT_MIN: 0,
   JAVASCRIPTVALTIMEOUT_MAX: 60000,
   
   DC_APPENDMODE_DEFAULT: 1,
   DC_APPENDMODE_SUBSCRIPT: 2,
   DC_APPENDMODE_INSERT: 3,

   HEADERTYPE_REQUEST: '1',
   HEADERTYPE_RESPONSE: '2',

   HEADER_MERGE: '1',
   HEADER_REPLACE: '2',

   URLMASK_TYPE_IGNORE: '1',
   URLMASK_TYPE_BLOCK: '2',

   URLMASK_STYLE_PLAINTEXT: '1',
   URLMASK_STYLE_REGEXP: '2',

   WMODETIMEOUT_MIN: 0,
   WMODETIMEOUT_MAX: 9999,

   BRANCH_CONDITION_DELIMITER: ':\t:',
   BRANCH_CONDITION_ALWAYS: '1',
   BRANCH_CONDITION_NEVER: '2',
   BRANCH_CONDITION_REPLAYSTATUS: '3',
   BRANCH_CONDITION_REPLAYSTATUSNOT: '4',

   BRANCH_TARGET_TYPE_END: '0',
   BRANCH_TARGET_TYPE_JUMP: '1',

   BRANCH_TARGET_DELIMITER: ':',
   BRANCH_TARGET_ACTION: 'action',
   BRANCH_TARGET_EVENT: 'event',
   BRANCH_TARGET_END: 'end',

   BRANCH_REPLAYSTATUS_0: '0',
   BRANCH_REPLAYSTATUS_1: '1',
   BRANCH_REPLAYSTATUS_2: '2',
   BRANCH_REPLAYSTATUS_5: '5',
   BRANCH_REPLAYSTATUS_7: '7',

   VALIDATION_TYPE_KEYWORD: '1',
   VALIDATION_TYPE_JAVASCRIPT: '2',
   VALIDATION_TYPE_IMAGE: '3',

   VALIDATION_KEYWORDMATCH_PLAIN: '1',
   VALIDATION_KEYWORDMATCH_REGEXP: '2',

   VALIDATION_KEYWORD_ACTION_ERROR: '1',
   VALIDATION_KEYWORD_ACTION_WAIT: '2',
   VALIDATION_KEYWORD_ACTION_CUSTOMERROR: '3',

   VALIDATION_KEYWORD_REQUIREMATCH: '1',
   VALIDATION_KEYWORD_FORBIDMATCH: '2',

   VALIDATION_KEYWORD_SEARCHALL: '1',
   VALIDATION_KEYWORD_SEARCHONE: '2',

   VALIDATION_JAVASCRIPT_ACTION_ERROR: '1',
   VALIDATION_JAVASCRIPT_ACTION_WAIT: '2',

   VALIDATION_JAVASCRIPT_ISFALSE: '1',
   VALIDATION_JAVASCRIPT_ISTRUE: '2',

   VALIDATION_JAVASCRIPT_EVALDEFAULT: '1',
   VALIDATION_JAVASCRIPT_EVALONE: '2',

   VARIABLE_TYPE: '1',

   DC_TOKENTYPE_STATICTEXT: '1',
   DC_TOKENTYPE_RANDOMTEXT: '2',
   DC_TOKENTYPE_RANDOMNUMBER: '3',
   DC_TOKENTYPE_AUTOINC: '4',
   DC_TOKENTYPE_DATETIME: '5',
   DC_TOKENTYPE_DATASET: '6',
   DC_TOKENTYPE_LOCATION: '7',
   DC_TOKENTYPE_JAVASCRIPT: '8',

   DC_SEPARATOR_TOKENPARAMS: ':\t:',
   DC_SEPARATOR_TOKENS: '|\t|',
   DC_VALIDRANDOMCHARS : "01234567890abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ",

   DC_SIMULATEMOBILE: 'simulatemobile',
   DC_SIMULATEMOBILE_CONTENT: 'simulatemobilecontent',
   DC_MOBILECONTENT_XHTML_MP: 'XHTML-MP',
   
   DC_DELIM_CONDITION: ':\t:',
   
   CONDITIONTYPE_ALWAYS: 1,
   CONDITIONTYPE_NEVER: 2,
   CONDITIONTYPE_REPLAYSTATUS: 3,
   CONDITIONTYPE_REPLAYSTATUS_NOT: 4,
   
   TARGETTYPE_ACTION: "action",
   TARGETTYPE_EVENT: "event",
   TARGETTYPE_ENDREPLAY: "end",

   MOBILEDEVICE_WIDTH_MIN: 120,
   MOBILEDEVICE_WIDTH_MAX: 4800,
   MOBILEDEVICE_HEIGHT_MIN: 160,
   MOBILEDEVICE_HEIGHT_MAX: 7680,

   DIALOGTYPE_LOGINPROMPT: '1',
   DIALOGTYPE_INPUTPROMPT: '2',
   DIALOGTYPE_CONFIRMPROMPT: '3',
   DIALOGTYPE_GENERICPROMPT: '4',
   DIALOGTYPE_CERTMISMATCH: '5',
   DIALOGTYPE_CERTUNKNOWN: '6',
   DIALOGTYPE_CERTEXPIRED: '7',
   DIALOGTYPE_CERTINVALID: '8',
   DIALOGTYPE_CERTCLIENT: '9',

   DIALOGOPTION_DEFAULT: '1',

   DIALOGBUTTON_ACCEPT: '1',
   DIALOGBUTTON_CANCEL: '2',
   DIALOGBUTTON_EXTRA1: '3',
   DIALOGBUTTON_EXTRA2: '4',

   DIALOGREPEAT_MIN: 1,
   DIALOGREPEAT_MAX: 99,

   CONTENTVIEW_TYPE: '1',
   CONTENTVIEW_DEFINITION_DELIMITER: '||',
   CONTENTVIEW_DEFINITION_ITEM_DELIMITER: '::',
   CONTENTVIEW_DEFINITION_CONTAINS: '1',
   CONTENTVIEW_DEFINITION_REFERENCES: '2',
   CONTENTVIEW_DEFINITION_PREDEFINED: '3',
   CONTENTVIEW_DEFINITION_PLAINTEXT: '1',
   CONTENTVIEW_DEFINITION_REGEXP: '2',
   CONTENTVIEW_DEFINITION_INCLUDE: '1',
   CONTENTVIEW_DEFINITION_EXCLUDE: '2',
   CONTENTVIEW_SCOPE_DELIMITER: '||',
   CONTENTVIEW_SCOPE_ITEM_DELIMITER: ':',

   DC_TRUESCREEN_SKIPLIST : "|text/html|application/xhtml+xml|image/svg+xml|application/vnd.mozilla.xul+xml|",
   
   // replay hint labels
   DC_THINKTIMEHINT : 'thinktime',
   DC_LOCATIONHINT : 'locations',
   DC_MUTATIONHINT : 'mutations',
   DC_SCRIPTINGHINT : 'scripting',
   DC_BROWSERHINT : 'browsers',
   DC_NETWORKHINT : 'netactivity',
   
   DC_SCRIPTEDCONTENT : 'dcscripted',   // dynamically scripted element
   DC_HOVEREVENTID : 'dcmouseid',       // scripted element mouseover
   DC_HOVERCONTENT : 'dcmousemove',     // element has mouse movement event handlers
   
   // replay status states
   DC_REPLAY_SUCCESS: 0,
   DC_REPLAY_WARNING: 1,
   DC_REPLAY_ERROR: 2,

   MAXERRORCOUNT: 20,   // maximum number of errors permitted during record/replay (prevents infinite looping)
      
   CAPTURE_COMPLETED: 1,
   TIMINGS_COMPLETED: 2,

   // URL providing help on writing regular expressions.
   REGEXP_HELP_URL: 'https://www.alertsite.com/cgi-bin/helpme.cgi?page=RegexMatching.html',

   NS_OK : 1,

   SIDEBAR_WIDTH: 440,
   WINDOW_RESIZE_MIN_WIDTH: 400,
   MAX_UPLOAD_SCRIPT_SIZE: 10 * 1024 * 1024

};
